#!/bin/sh

case "$1" in
    start)

        air_man &>/dev/null &

        ;;
    stop)
        killall -q air_man
        esac
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
