#!/bin/sh

case "$1" in
    start)
        
        # Read alink mode from YAML
        alink="$(yaml-cli -i /etc/wfb.yaml -g .wireless.link_control)"

        # If empty or unknown, treat as disabled
        case "$alink" in
            alink)
                echo "Control mode: alink"
                # Put the commands you need for starting 'alink' here
                alink_drone &>/dev/null &
                ;;
            ""|disabled|*)
                # If empty, explicitly "disabled", or unrecognized value
                echo "alink mode is 'disabled' (or unrecognized), skipping alink start."
                ;;
        esac
        ;;

    stop)
        # Read alink mode again
        alink="$(yaml-cli -i /etc/wfb.yaml -g .wireless.alink)"

        # Stop whichever mode was started
        case "$alink" in
            alink)
                echo "Stopping alink..."
                killall -q alink_drone
                ;;
            ""|disabled|*)
                echo "alink mode is 'disabled' (or unrecognized), nothing to stop."
                ;;
        esac
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
